export const items =[
    { name: "chills" },
    { name: "appetite loss" },
    { name: "deviated septum" },
    { name: "phlegm" },
    { name: "choking" },
    { name: "breathlessness" },
    { name: "pain during bowel movements" },
    { name: "salivation" },
    { name: "bloody stool" },
    { name: "underweight" },
    { name: "yellow crust ooze" },
    { name: "headache" },
    { name: "cold hands and feets" },
    { name: "joint pain" },
    { name: "cystic fibrosis" },
    { name: "loss of appetite" },
    { name: "continuous feel of urine" },
    { name: "urban living" },
    { name: "asthma" },
    { name: "pregnant" },
    { name: "kidney failure" },
    { name: "rectal bleeding" },
    { name: "irritability" },
    { name: "muscle weakness" },
    { name: "red sore around nose" },
    { name: "post cough vomiting" },
    { name: "palpitations" },
    { name: "silver like dusting" },
    { name: "secondhand smoke" },
    { name: "premature birth" },
    { name: "watering from eyes" },
    { name: "pain" },
    { name: "skin rash" },
    { name: "wheez sound after cough" },
    { name: "hemoptysis" },
    { name: "dehydration" },
    { name: "dischromic  patches" },
    { name: "rash intensity" },
    { name: "blister" },
    { name: "copd" },
    { name: "blackheads" },
    { name: "belly pain" },
    { name: "dyspnea" },
    { name: "sore throat" },
    { name: "bruising" },
    { name: "small dents in nails" },
    { name: "abnormal menstruation" },
    { name: "drug use" },
    { name: "drying and tingling lips" },
    { name: "nocturnal symptoms" },
    { name: "dark urine" },
    { name: "large lesions" },
    { name: "swollen legs" },
    { name: "malaise" },
    { name: "fatigue" },
    { name: "acute liver failure" },
    { name: "muscle wasting" },
    { name: "congestion" },
    { name: "red spots over body" },
    { name: "inflammatory nails" },
    { name: "weight gain" },
    { name: "vaccinated" },
    { name: "swollen blood vessels" },
    { name: "high pitch sound when breathing in" },
    { name: "blood in sputum" },
    { name: "weight loss" },
    { name: "anxiety" },
    { name: "hip joint pain" },
    { name: "irritation in anus" },
    { name: "patches in throat" },
    { name: "cramps" },
    { name: "crowded home" },
    { name: "indigestion" },
    { name: "blurred and distorted vision" },
    { name: "spotting  urination" },
    { name: "neck pain" },
    { name: "polyuria" },
    { name: "head trauma" },
    { name: "dizziness" },
    { name: "enlarged thyroid" },
    { name: "mood swings" },
    { name: "spinning movements" },
    { name: "skin peeling" },
    { name: "anosmia" },
    { name: "sweating" },
    { name: "family asthma" },
    { name: "nodal skin eruptions" },
    { name: "swollen extremeties" },
    { name: "fibromyalgia" },
    { name: "swelling joints" },
    { name: "family history" },
    { name: "lethargy" },
    { name: "bilateral paresthesia" },
    { name: "anemia history" },
    { name: "yellowish skin" },
    { name: "bloating" },
    { name: "pain relief leaning" },
    { name: "sinus pressure" },
    { name: "travelled outisde country" },
    { name: "slurred speech" },
    { name: "rusty sputum" },
    { name: "receiving unsterile injections" },
    { name: "poor diet" },
    { name: "irregular sugar level" },
    { name: "long menstrual period" },
    { name: "purulent rhinitis" },
    { name: "recent cold" },
    { name: "shivering" },
    { name: "fear of death" },
    { name: "passage of gases" },
    { name: "hypertension" },
    { name: "toxic look (typhos)" },
    { name: "continuous sneezing" },
    { name: "burning micturition" },
    { name: "runny nose" },
    { name: "back pain" },
    { name: "allergy prone" },
    { name: "constipation" },
    { name: "abdominal pain" },
    { name: "internal itching" },
    { name: "stomach pain" },
    { name: "brittle nails" },
    { name: "stomach bleeding" },
    { name: "diabetes" },
    { name: "nausea" },
    { name: "sinusitis" },
    { name: "increased appetite" },
    { name: "loss of smell" },
    { name: "productive cough" },
    { name: "peeling skin" },
    { name: "excessive hunger" },
    { name: "ulcers on tongue" },
    { name: "mild fever" },
    { name: "visual disturbances" },
    { name: "general paresthesia" },
    { name: "receiving blood transfusion" },
    { name: "fluid overload" },
    { name: "movement stiffness" },
    { name: "acidity" },
    { name: "throat irritation" },
    { name: "weakness of one body side" },
    { name: "depression" },
    { name: "rash location" },
    { name: "nasal polyps" },
    { name: "immuno suppressed" },
    { name: "obstipation" },
    { name: "yellowing of eyes" },
    { name: "foul smell of urine" },
    { name: "mucoid sputum" },
    { name: "severe cough" },
    { name: "dysphagia" },
    { name: "asian descent" },
    { name: "hoarse voice" },
    { name: "no travel" },
    { name: "weakness in limbs" },
    { name: "family migraines" },
    { name: "smoking" },
    { name: "sunken eyes" },
    { name: "depersonalization" },
    { name: "high fever" },
    { name: "stiff neck" },
    { name: "coma" },
    { name: "diarrhoea" },
    { name: "asthma attacks" },
    { name: "chest pain" },
    { name: "skin lesions" },
    { name: "obesity" },
    { name: "swollen rash" },
    { name: "altered sensorium" },
    { name: "gastroesophageal reflux" },
    { name: "unsteadiness" },
    { name: "lack of concentration" },
    { name: "pertussis contact" },
    { name: "bladder discomfort" },
    { name: "paleness" },
    { name: "extra marital contacts" },
    { name: "redness of eyes" },
    { name: "work daycare" },
    { name: "pneumonia" },
    { name: "swelled lymph nodes" },
    { name: "faintness" },
    { name: "painful walking" },
    { name: "crohns" },
    { name: "prominent veins on calf" },
    { name: "pain behind the eyes" },
    { name: "rheumatoid arthritis" },
    { name: "pain in anal region" },
    { name: "puffy face and eyes" },
    { name: "diaphoresis" },
    { name: "alcoholism" },
    { name: "family anemia" },
    { name: "restlessness" },
    { name: "anticoagulants" },
    { name: "fast heart rate" },
    { name: "yellow urine" },
    { name: "rash color" },
    { name: "knee pain" },
    { name: "history of alcohol consumption" },
    { name: "valsalva symptoms" },
    { name: "chronic anxiety" },
    { name: "fever" },
    { name: "contact with similar symptoms person" },
    { name: "muscle pain" },
    { name: "distention of abdomen" },
    { name: "vomiting" },
    { name: "scurring" },
    { name: "ear infection" },
    { name: "loss of balance" },
    { name: "family psychiatric history" },
    { name: "wheez sound when exhale" },
    { name: "itching" },
    { name: "cough" },
    { name: "pus filled pimples" },
  ];
  


